/* -----------------------------------------------------------------------------
 * Part of midgetv
 * 2019. Copyright B. Nossum.
 * For licence, see LICENCE
 * -----------------------------------------------------------------------------
 * Generate initial values for the microcode of midgetv
 */
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <inttypes.h>

#define ferr(...) exit( fprintf(stderr, __VA_ARGS__))

// Defeat quoting system of some shells
#define STRX(x) # x
#define STR(x) STRX(x)
#define fname STR(nakedfname)

// Number of equations. Here I do not count the 8-bit next address
#define NREQATIONS 34

/* The specification is in ucode.h.
 */
typedef enum {
#define X(label,txt,def) label,
#include fname
        _LEND
} LABELS;

char *labeltext[256] = {
#define X(label,txt,def) STR(label),
#include fname
};

char *ucodestr[256] = {
#define X(label,txt,def) txt,
#include fname
};

uint64_t ucode0[256] = {
#define x 0b0
#define X(label,txt,def) def,
#include fname
};

uint64_t ucode1[256] = {
#define x 0b1
#define X(label,txt,def) def,
#include fname
};

#ifndef STRIPCOLUMNS
#define STRIPCOLUMNS 0
#endif


int statistics_on_unknown[NREQATIONS];

/////////////////////////////////////////////////////////////////////////////
int main( int argc __attribute__((unused)), char *argv[] ) {
        int k,kk,j;
        uint16_t rom[4][256];
        
        if ( _LEND != 256 )
                ferr( "Wrong number of microcode instructions\n" );
        printf( 
                "/* -------------------------------------"
                "----------------------------------------\n"
                " * Part of midgetv\n"
                " * 2019. Copyright B. Nossum.\n"
                " * For licence, see LICENCE\n"
                " * -------------------------------------"
                "----------------------------------------\n"
                " * Automaticaly generated by %s (based on %s).\n"
                " * Do not edit.\n"
                " *\n", argv[0], fname );
        printf( " * uPC\n" );
        printf( " * ||            next uPC\n");
        printf( " * ||            || ucodeInstruction\n" );
        printf( " * ||            || " );
        for ( k = NREQATIONS-1; k >= 10; k-- )
                printf( "%d", k / 10 );
        printf( "\n" );
        printf( " * || label      || " );
        for ( k = NREQATIONS-1; k >= 0; k-- )
                printf( "%d", k % 10 );
        printf( " Purpose\n" );
        printf( " * -- ---------- -- %.*s --------------"
                "----------------------------------------\n", NREQATIONS, "---------------------------------------" );
        for ( k = 0; k < 256; k++ ) { 
                printf( " * %2.2x ", k );
                printf( "%-10s ", labeltext[k] );
                int next = (( ucode0[k] >> NREQATIONS) & 255);
                if ( next ) {
                        printf( "%2.2x ", next );
                } else {
                        printf( "   " );
                }
                
                //printf( "%16.16" PRIx64 " ", ucode[k]);
                for ( int i = NREQATIONS-1; i >= 0; i-- ) {                        
                        int b_a = (( ucode0[k] >>i) & 1);
                        int b_b = (( ucode1[k] >>i) & 1);
                        printf( "%c", b_a == b_b ? '0'+b_a : 'x' );

                        statistics_on_unknown[i] += (b_a^b_b);
                }
                printf( " " );
                
                printf( "%s\n" , ucodestr[k] );
        }
        printf( " */\n" );

#if 0
        // As a tool for later optimalization, print statistics on nr of unknowns in each column.
        printf( "/* Col NrUnknwons\n" );
        for ( int i = NREQATIONS-1; i >= 0; i-- ) 
                printf( " * %3d %3d\n", i, statistics_on_unknown[i] );
        printf( " */\n" );
#endif
        
        // Convert the 256 deep 64 bit wide ucode to
        // 4 256 deep 16 bit wide, this is a simple slicing.
        for ( kk = 0; kk < 4; kk++ ) 
                for ( k = 0; k < 256; k++ ) 
                        rom[kk][k] = (ucode0[k] >> (16*kk)) & 0xffff;

        // Write out each of the ROMs in use with 16 entries in each INIT_x
#define NRROMS 3        
        for ( kk = 0; kk < NRROMS; kk++ ) {
                for ( k = 0; k < 16; k++ ) {
                        printf( "localparam u%d_%X = 256'h", kk, k );
                        for ( j = 15; j >= 0; j-- ) 
                                printf( "%4.4x", rom[kk][k*16+j] );
                        printf( ";\n" );
                }
        }
        
        return 0;
}
