/* -----------------------------------------------------------------------------
 * Part of midgetv
 * 2019. Copyright B. Nossum.
 * For licence, see LICENCE
 * -----------------------------------------------------------------------------
 * We undefine the short defines that has been used in this file
 */
#undef Y
#undef X
#undef XX
#undef I 
#undef II 
#undef III
#undef IIII 
#undef IIIII
#undef IIIIIO 
#undef IIIIO
#undef IIIO 
#undef IIIOI
#undef IIIOII 
#undef IIIOO
#undef IIIOOO 
#undef IIO
#undef IIOI 
#undef IIOII
#undef IIOIO
#undef IIOO 
#undef IIOOI
#undef IIOOO
#undef IO 
#undef IOI
#undef IOII 
#undef IOIII
#undef IOIIO
#undef IOIO 
#undef IOIOI
#undef IOIOO
#undef IOIOOO 
#undef IOO
#undef IOOI 
#undef IOOII
#undef IOOO 
#undef IOOOI
#undef IOOOO
#undef O 
#undef OI 
#undef OII
#undef OIII 
#undef OIIO 
#undef OIIOO
#undef OIIOOO 
#undef OIIxx
#undef OIO
#undef OIOI 
#undef OIOO 
#undef OIOxx 
#undef OO 
#undef OOI
#undef OOII 
#undef OOIO 
#undef OOIOI
#undef OOIOIO 
#undef OOIOO
#undef OOIOOI 
#undef OOIOOO 
#undef OOIxx 
#undef OOO
#undef OOOI 
#undef OOOII
#undef OOOIO
#undef OOOO 
#undef OOOOI
#undef OOOOO
#undef OOOxx
#undef Ox 
#undef Oxxx 
#undef x 
#undef xI 
#undef xO 
#undef xx 
#undef xxI
#undef xxxx 
#undef xxxxx 


